- name: check the tomcat running ore not
  hosts: all
  tasks: 
    - name: check tomcat is up or not
      ansible.builtin.shell: ps -ef | grep java | grep -v grep
      register: OUT
      ignore_errors: yes

    - name: starting tomcat
      ansible.builtin.debug:
       msg: starttomcat
